### ISSUE TITLE
Nice Error Handling you guys have

### ISSUE THREAD

**Issue by McFarts** [MSOpenTech/redis#307]
What a complete joke.

![](https://i.gyazo.com/3f54ef69eb3e8771ebba1a8e01d0c093.png)

Windows 7 64 bit Pro here, what's the problem?

**Comment by satish860** [comment]
Looks like this https://github.com/MSOpenTech/redis/issues/304

**Comment by enricogior** [comment]
@McFarts 
does the problem still persist with [2.8.2103](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2103)?
Thank you.

**Comment by McFarts** [comment]
@enricogior  Nope! 

![](https://i.gyazo.com/5a829bf27d136cc32af61bbf08d9dde0.png)

I wouldn't of re-downloaded it either but you guys seem professional here after my acetone text.  Works fine now though :)
